server:
  port: 80 #80端口是默认http端口，在网址中不出现（如http://localhost/consumer/dept/lsit）
# 通过eureka访问provider-dept-8001等微服务

feign:  # 服务熔断、降级
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false  # false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/